---
- name: Upgrade OS
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  async: 1800
  poll: 20

- name: Download installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/{{ hestia_install_script }}
    dest: /root/{{ hestia_install_script }}
    mode: "644"

- name: Run installation
  ansible.builtin.command:
    cmd: >
      bash /root/{{ hestia_install_script }}
      --interactive no
      --force
      --port {{ hestia_install_opt.port }}
      --hostname {{ hestia_hostname }}
      --username {{ hestia_username }}
      --email {{ hestia_admin_mail }}
      --password {{ hestia_admin_password }}
      --apache {{ hestia_install_opt.apache }}
      --phpfpm {{ hestia_install_opt.phpfpm }}
      --multiphp '{{ hestia_install_opt.multiphp | join(",") }}'
      --vsftpd {{ hestia_install_opt.vsftpd }}
      --proftpd {{ hestia_install_opt.proftpd }}
      --named {{ hestia_install_opt.named }}
      --mysql {{ hestia_install_opt.mysql }}
      --mysql8 {{ hestia_install_opt.mysql8 }}
      --postgresql {{ hestia_install_opt.postgresql }}
      --exim {{ hestia_install_opt.exim }}
      --dovecot {{ hestia_install_opt.dovecot }}
      --sieve {{ hestia_install_opt.sieve }}
      --clamav {{ hestia_install_opt.clamav }}
      --spamassassin {{ hestia_install_opt.spamassassin }}
      --iptables {{ hestia_install_opt.iptables }}
      --fail2ban {{ hestia_install_opt.fail2ban }}
      --quota {{ hestia_install_opt.quota }}
      --api {{ hestia_install_opt.api }}
  args:
    creates: /usr/local/hestia
  async: 3600
  poll: 20
  notify: Reboot server

- name: Set custom NS for the default package
  ansible.builtin.lineinfile:
    path: /usr/local/hestia/data/packages/default.pkg
    regexp: '^NS='
    line: "NS='{{ hestia_nameserver_1 }},{{ hestia_nameserver_2 }}'"

- name: Update NS for sysadmin user
  ansible.builtin.command:
    cmd: /usr/local/hestia/bin/v-change-user-ns {{ hestia_username }} {{ hestia_nameserver_1 }} {{ hestia_nameserver_2 }}
  changed_when: true

- name: Create DNS Zone for domain
  ansible.builtin.command:
    cmd: /usr/local/hestia/bin/v-add-dns-domain {{ hestia_username }} {{ hestia_hostname }} {{ ansible_default_ipv4.address }}
  changed_when: true
